Aplicaciones/Historiales/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('listadoRepresentantes/',views.listadoRepresentantes),
    path('guardarRepresentante/',views.guardarRepresentante),
    path('eliminarRepresentante/<id>',views.eliminarRepresentante),
    path('editarRepresentante/<id>', views.editarRepresentante, name='editarRepresentante'),
    path('procesarActualizacionRepresentante/<id>', views.procesarActualizacionRepresentante, name='procesarActualizacionRepresentante'),




    path('listadoDoctores/',views.listadoDoctores),
    path('guardarDoctor/',views.guardarDoctor),
    path('eliminarDoctor/<id>',views.eliminarDoctor),
    path('editarDoctor/<id>', views.editarDoctor, name='editarDoctor'),
    path('procesarActualizacionDoctor/<id>', views.procesarActualizacionDoctor, name='procesarActualizacionDoctor'),


    path('listadoMedicamento/', views.listadoMedicamentos),
    path('guardarMedicamento/', views.guardarMedicamento),
    path('eliminarMedicamento/<id>/', views.eliminarMedicamento),
    path('editarMedicamento/<id>/', views.editarMedicamento, name='editarMedicamento'),
    path('procesarActualizacionMedicamento/<id>/', views.procesarActualizacionMedicamento, name='procesarActualizacionMedicamento'),


    path('listadoPacientes/', views.listadoPacientes, name='listadoPacientes'),
    path('guardarPaciente/', views.guardarPaciente, name='guardarPaciente'),
    path('eliminarPaciente/<int:id>/', views.eliminarPaciente, name='eliminarPaciente'),
    path('editarPaciente/<int:id>/', views.editarPaciente, name='editarPaciente'),
    path('procesarActualizacionPaciente/<int:id>/', views.procesarActualizacionPaciente, name='procesarActualizacionPaciente'),



    path('',views.listadoHistoriales),
    path('guardarHistorial/',views.guardarHistorial),
    path('eliminarHistorial/<id>',views.eliminarHistorial),


    path('listadoCitas/',views.listadoCitas),
    path('guardarCita/',views.guardarCita),
    path('eliminarCita/<idCita>',views.eliminarCita),
    path('editarCita/<idCita>', views.editarCita, name='editarCita'),
    path('procesarActualizacionCita/<idCita>', views.procesarActualizacionCita, name='procesarActualizacionCita'),


    path('listadoRecetas/',views.listadoRecetas),
    path('guardarReceta/',views.guardarReceta),
    path('eliminarReceta/<idReceta>',views.eliminarReceta),
    path('editarReceta/<idReceta>', views.editarReceta, name='editarReceta'),
    path('procesarActualizacionReceta/<idReceta>', views.procesarActualizacionReceta, name='procesarActualizacionReceta'),


    path('listadoDetalles/', views.listadoDetalles),
    path('guardarDetalle/', views.guardarDetalle),
    path('eliminarDetalle/<int:idDetalle>/', views.eliminarDetalle),
    path('editarDetalle/<int:idDetalle>/', views.editarDetalle, name='editarDetalle'),
    path('procesarActualizacionDetalle/<int:idDetalle>/', views.procesarActualizacionDetalle, name='procesarActualizacionDetalle'),



    path('reporte/<id>',views.reporte),


    path('info/<idCita>',views.info),
]

MediKid/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Aplicaciones.Historiales.urls'))
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Aplicaciones/Historiales/models.py
from django.db import models

# Create your models here.
class Representante(models.Model):
    id=models.AutoField(primary_key=True)
    nombreRepresentante=models.CharField(max_length=150)
    apellidoRepresentante=models.CharField(max_length=150)
    cedulaRepresentante=models.CharField(max_length=10)
    telefonoRepresentante=models.CharField(max_length=10)
    nacionalidadRepresentante=models.CharField(max_length=150)
    correoRepresentante=models.EmailField()
    direccionRepresentante=models.TextField()

    def __str__(self):
        fila="- {0}"
        return fila.format(self.nombreRepresentante)


class Doctor(models.Model):
    id=models.AutoField(primary_key=True)
    nombreDoctor=models.CharField(max_length=150)
    apellidoDoctor=models.CharField(max_length=150)
    cedulaDoctor=models.CharField(max_length=10)
    telefonoDoctor=models.CharField(max_length=10)
    fechaNacimientoDoctor=models.DateField()
    especialidadDoctor=models.CharField(max_length=150)
    correoDoctor=models.EmailField()
    fotoDoctor=models.FileField(upload_to='doctores',null=True,blank=True)
    direccionDoctor=models.TextField()

    def __str__(self):
        fila="- {0}"
        return fila.format(self.nombreDoctor)


class Medicamento(models.Model):
    id = models.AutoField(primary_key=True)
    nombreMedicamento = models.CharField(max_length=150)
    dosisMedicamento = models.CharField(max_length=50)
    tipoMedicamento = models.CharField(max_length=150)
    precaucionesMedicamento = models.TextField()

    def __str__(self):
        fila = "- {0}"
        return fila.format(self.nombreMedicamento)



#tabla paciente-relacion con representante
class Paciente(models.Model):
    idPaciente = models.AutoField(primary_key=True)
    nombrePaciente = models.CharField(max_length=150)
    apellidoPaciente = models.CharField(max_length=150)
    cedulaPaciente = models.CharField(max_length=10)
    fechaNacimientoPaciente = models.DateField()
    nacionalidadPaciente = models.CharField(max_length=150)
    representante = models.ForeignKey(Representante, on_delete=models.PROTECT)

    def __str__(self):
        fila = "-{0}"
        return fila.format(self.nombrePaciente)


class Historial(models.Model):
    id = models.AutoField(primary_key=True)
    paciente = models.OneToOneField(Paciente, on_delete=models.PROTECT)
    fechaCreacion = models.DateField()

    def __str__(self):
        fila = "Historial de {1} del {0}"
        return fila.format(self.paciente,self.fechaCreacion)

class Cita(models.Model):
    idCita = models.AutoField(primary_key=True)
    fechaCreacion = models.DateField()
    doctor = models.ForeignKey(Doctor, on_delete=models.PROTECT)
    historial = models.ForeignKey(Historial, on_delete=models.PROTECT)

    def __str__(self):
        fila = "Cita de {0} el {1}"
        return fila.format(self.doctor,self.fechaCreacion)


class Receta(models.Model):
    idReceta = models.AutoField(primary_key=True)
    fechaCreacion = models.DateField()
    altura = models.CharField(max_length=10)
    peso = models.CharField(max_length=10)
    cita = models.OneToOneField(Cita,null=True,blank=True, on_delete=models.PROTECT)


    def __str__(self):
        fila = "Receta creada el -{0}"
        return fila.format(self.fechaCreacion)


class Detalle(models.Model):
    idDetalle = models.AutoField(primary_key=True)
    cantidad = models.CharField(max_length=50)
    frecuencia = models.CharField(max_length=50)
    duracion = models.CharField(max_length=50)
    medicamento = models.ForeignKey(Medicamento, on_delete=models.PROTECT)
    receta = models.ForeignKey(Receta, on_delete=models.CASCADE)    

    def __str__(self):
        fila = "-{0}"
        return fila.format(self.cantidad)

Aplicaciones/Historiales/views.py
from django.shortcuts import render, redirect
from .models import Representante, Doctor, Medicamento, Paciente, Historial, Receta, Cita, Detalle
from django.contrib import messages
from django.conf import settings
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
# Create your views here.
def listadoRepresentantes(request):
    repreBdd=Representante.objects.all()
    return render(request,'listadoRepresentantes.html',{'representantes':repreBdd})


def guardarRepresentante(request):
    nombreRepresentante=request.POST["nombreRepresentante"]
    apellidoRepresentante=request.POST["apellidoRepresentante"]
    cedulaRepresentante=request.POST["cedulaRepresentante"]
    telefonoRepresentante=request.POST["telefonoRepresentante"]
    correoRepresentante=request.POST["correoRepresentante"]
    nacionalidadRepresentante=request.POST["nacionalidadRepresentante"]
    direccionRepresentante=request.POST["direccionRepresentante"]



    nuevoRepresentante = Representante.objects.create(
        nombreRepresentante=nombreRepresentante,
        apellidoRepresentante=apellidoRepresentante,
        cedulaRepresentante=cedulaRepresentante,
        telefonoRepresentante=telefonoRepresentante,
        correoRepresentante=correoRepresentante,
        nacionalidadRepresentante=nacionalidadRepresentante,
        direccionRepresentante=direccionRepresentante,
    )

    messages.success(request, 'Representante guardado exitosamente')
    send_mail("CREACIÓN DE REPRESENTANTE", "SE HA CREADO "+nombreRepresentante, settings.EMAIL_HOST_USER, ["trabajos.utc.ejemplos@gmail.com"], fail_silently=False )
    return redirect('/listadoRepresentantes')


def eliminarRepresentante(request,id):
    eliminarRepresentante=Representante.objects.get(id=id)
    eliminarRepresentante.delete()
    return redirect('/listadoRepresentantes')

def editarRepresentante(request, id):
    reprEditar = Representante.objects.get(id=id)
    return render(request, 'editarRepresentante.html', {'representante': reprEditar})


def procesarActualizacionRepresentante(request, id):
    id = request.POST["id"]
    nombreRepresentante = request.POST["nombreRepresentante"]
    apellidoRepresentante = request.POST["apellidoRepresentante"]
    cedulaRepresentante = request.POST["cedulaRepresentante"]
    telefonoRepresentante = request.POST["telefonoRepresentante"]
    correoRepresentante = request.POST["correoRepresentante"]
    nacionalidadRepresentante = request.POST["nacionalidadRepresentante"]
    direccionRepresentante = request.POST["direccionRepresentante"]

    reprEditar = Representante.objects.get(id=id)
    reprEditar.nombreRepresentante = nombreRepresentante
    reprEditar.apellidoRepresentante = apellidoRepresentante
    reprEditar.cedulaRepresentante = cedulaRepresentante
    reprEditar.telefonoRepresentante = telefonoRepresentante
    reprEditar.correoRepresentante = correoRepresentante
    reprEditar.nacionalidadRepresentante = nacionalidadRepresentante
    reprEditar.direccionRepresentante = direccionRepresentante
    reprEditar.save()

    messages.success(request, 'Representante actualizado exitosamente')
    return redirect('/listadoRepresentantes')


#Fin de Clases representantes



def listadoDoctores(request):
    doctorBdd=Doctor.objects.all()
    return render(request,'listadoDoctores.html',{'doctores':doctorBdd})


def guardarDoctor(request):
    nombreDoctor=request.POST["nombreDoctor"]
    apellidoDoctor=request.POST["apellidoDoctor"]
    cedulaDoctor=request.POST["cedulaDoctor"]
    telefonoDoctor=request.POST["telefonoDoctor"]
    fechaNacimientoDoctor=request.POST["fechaNacimientoDoctor"]
    especialidadDoctor=request.POST["especialidadDoctor"]
    correoDoctor=request.POST["correoDoctor"]
    direccionDoctor=request.POST["direccionDoctor"]
    fotoDoctor=request.FILES.get("fotoDoctor")

    nuevoDoctor = Doctor.objects.create(
        nombreDoctor=nombreDoctor,
        apellidoDoctor=apellidoDoctor,
        cedulaDoctor=cedulaDoctor,
        telefonoDoctor=telefonoDoctor,
        correoDoctor=correoDoctor,
        especialidadDoctor=especialidadDoctor,
        fechaNacimientoDoctor=fechaNacimientoDoctor,
        direccionDoctor=direccionDoctor,
        fotoDoctor=fotoDoctor,
    )

    messages.success(request, 'Doctor guardado exitosamente')
    send_mail("CREACIÓN DE DOCTOR", "SE HA CREADO "+nombreDoctor, settings.EMAIL_HOST_USER, ["trabajos.utc.ejemplos@gmail.com"], fail_silently=False )
    return redirect('/listadoDoctores')



def eliminarDoctor(request,id):
    eliminarDoctor=Doctor.objects.get(id=id)
    eliminarDoctor.delete()
    return redirect('/listadoDoctores')

def editarDoctor(request, id):
    docEditar = Doctor.objects.get(id=id)
    return render(request, 'editarDoctor.html', {'doctor': docEditar})


def procesarActualizacionDoctor(request, id):
    id = request.POST["id"]
    nombreDoctor=request.POST["nombreDoctor"]
    apellidoDoctor=request.POST["apellidoDoctor"]
    cedulaDoctor=request.POST["cedulaDoctor"]
    telefonoDoctor=request.POST["telefonoDoctor"]
    fechaNacimientoDoctor=request.POST["fechaNacimientoDoctor"]
    especialidadDoctor=request.POST["especialidadDoctor"]
    correoDoctor=request.POST["correoDoctor"]
    direccionDoctor=request.POST["direccionDoctor"]
    fotoDoctor=request.FILES.get("fotoDoctor")

    docEditar = Doctor.objects.get(id=id)
    docEditar.nombreDoctor = nombreDoctor
    docEditar.apellidoDoctor = apellidoDoctor
    docEditar.cedulaDoctor = cedulaDoctor
    docEditar.telefonoDoctor = telefonoDoctor
    docEditar.fechaNacimientoDoctor = fechaNacimientoDoctor
    docEditar.especialidadDoctor = especialidadDoctor
    docEditar.correoDoctor = correoDoctor
    docEditar.fotoDoctor = fotoDoctor
    docEditar.direccionDoctor = direccionDoctor
    docEditar.save()

    messages.success(request, 'Doctor actualizado exitosamente')
    return redirect('/listadoDoctores')

#inicia la clase de medicamento

def listadoMedicamentos(request):
    medicamentos = Medicamento.objects.all()
    return render(request, 'listadoMedicamentos.html', {'medicamentos': medicamentos})


def guardarMedicamento(request):
    if request.method == 'POST':
        nombreMedicamento = request.POST["nombreMedicamento"]
        dosisMedicamento = request.POST["dosisMedicamento"]
        tipoMedicamento = request.POST["tipoMedicamento"]
        precaucionesMedicamento = request.POST["precaucionesMedicamento"]

        Medicamento.objects.create(
            nombreMedicamento=nombreMedicamento,
            dosisMedicamento=dosisMedicamento,
            tipoMedicamento=tipoMedicamento,
            precaucionesMedicamento=precaucionesMedicamento,
        )

    messages.success(request, 'Medicamento guardado exitosamente')
    send_mail("CREACIÓN DE MEDICAMENTO", "SE HA CREADO "+nombreMedicamento, settings.EMAIL_HOST_USER, ["trabajos.utc.ejemplos@gmail.com"], fail_silently=False )
    return redirect('/listadoMedicamento')


def eliminarMedicamento(request, id):
    Medicamento.objects.filter(id=id).delete()
    return redirect('/listadoMedicamento')


def editarMedicamento(request, id):
    medicamento = Medicamento.objects.get(id=id)
    return render(request, 'editarMedicamento.html', {'medicamento': medicamento})



def procesarActualizacionMedicamento(request, id):
    if request.method == 'POST':
        nombreMedicamento = request.POST["nombreMedicamento"]
        dosisMedicamento = request.POST["dosisMedicamento"]
        tipoMedicamento = request.POST["tipoMedicamento"]
        precaucionesMedicamento = request.POST["precaucionesMedicamento"]

        medicamento = Medicamento.objects.get(id=id)
        medicamento.nombreMedicamento = nombreMedicamento
        medicamento.dosisMedicamento = dosisMedicamento
        medicamento.tipoMedicamento = tipoMedicamento
        medicamento.precaucionesMedicamento = precaucionesMedicamento
        medicamento.save()

        messages.success(request, 'Medicamento actualizado exitosamente')
    return redirect('/listadoMedicamento/')




#fin de la clase medicamento

#inicio de la calse pacientes

def listadoPacientes(request):
    pacientes = Paciente.objects.all()
    representantes = Representante.objects.all()
    return render(request, 'listadoPacientes.html', {'pacientes': pacientes, 'representantes': representantes})



def guardarPaciente(request):
    if request.method == 'POST':
        nombrePaciente = request.POST["nombrePaciente"]
        apellidoPaciente = request.POST["apellidoPaciente"]
        cedulaPaciente = request.POST["cedulaPaciente"]
        fechaNacimientoPaciente = request.POST["fechaNacimientoPaciente"]
        nacionalidadPaciente = request.POST["nacionalidadPaciente"]
        representante_id = request.POST["representante_id"]

        nuevoPaciente = Paciente.objects.create(
            nombrePaciente=nombrePaciente,
            apellidoPaciente=apellidoPaciente,
            cedulaPaciente=cedulaPaciente,
            fechaNacimientoPaciente=fechaNacimientoPaciente,
            nacionalidadPaciente=nacionalidadPaciente,
            representante_id=representante_id,
        )

        messages.success(request, 'Paciente guardado exitosamente')
        return redirect('/listadoPacientes')
        send_mail("CREACIÓN DEL PACIENTE", "SE HA CREADO "+nombrePaciente, settings.EMAIL_HOST_USER, ["trabajos.utc.ejemplos@gmail.com"], fail_silently=False )
        return redirect('/listadoPacientes')



def eliminarPaciente(request, id):
    paciente = Paciente.objects.get(idPaciente=id)
    paciente.delete()
    return redirect('listadoPacientes')




def editarPaciente(request, id):
    paciente = Paciente.objects.get(idPaciente=id)
    representantes = Representante.objects.all()
    return render(request, 'editarPaciente.html', {'paciente': paciente, 'representantes': representantes})



def procesarActualizacionPaciente(request, id):
    idPaciente = id
    nombrePaciente = request.POST["nombrePaciente"]

Aplicaciones/Historiales/templates/editarReceta.html
{% extends './plantilla.html' %}
{% block contenido %}



<!-- Sales Chart Start -->
<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
      <div class="bg-light text-center rounded p-4">
          <div class="d-flex align-items-center justify-content-between mb-4">
              <h6 class="mb-0">Editar Receta</h6>
          </div>
          <form class="" action="/procesarActualizacionReceta/{{receta.idReceta}}" enctype="multipart/form-data" method="post" id="frm_nuevo_historial">
            {% csrf_token %}
            <input type="hidden" name="idReceta" value="{{receta.idReceta}}">
            <div class="form-floating mb-3">
              <input type="date" class="form-control" name="fechaCreacion" id="fechaCreacion"placeholder="name@example.com" required>
              <label for="fechaCreacion">Fecha de Modificación</label>
              <div id="error-fechaCreacion" class="error-messages"></div>
            </div>
            <script>
              var fechaActual = new Date();
              var inputFecha = document.getElementById('fechaCreacion');

              inputFecha.onchange = function() {
                var fechaSeleccionada = new Date(this.value);
                if (fechaSeleccionada > fechaActual) {
                  inputFecha.value = fechaActual.toISOString().slice(0, 10);
                }
              };
            </script>


            <div class="form-floating mb-3">
              <input type="number" value="{{receta.peso}}" class="form-control" name="peso" id="peso"placeholder="name@example.com" required>
              <label for="peso">Peso del paciente (Klg)</label>
              <div id="error-peso" class="error-messages"></div>
            </div>

            <div class="form-floating mb-3">
              <input type="number" value="{{receta.altura}}"class="form-control" name="altura" id="altura"placeholder="name@example.com" required>
              <label for="altura">Altura del paciente (m)</label>
              <div id="error-altura" class="error-messages"></div>
            </div>

            <div class="form-floating mb-3">
              <select  name="id_cita"  id="id_cita" class="form-control" required>
                      <option value=""> Seleccionar la receta del paciente</option>
                      {% for cita in citas %}
                      <option value="{{cita.idCita}}">De {{cita.doctor.nombreDoctor}} el {{cita.fechaCreacion}}</option>
                      {% endfor %}
              </select>
              <label for="id_historial">Historial</label>
              <div id="error-id_cita" class="error-messages"></div>
            </div>

            <br>
            <button type="submit" name="button" class="btn btn-outline-info rounded-pill m-2">Guardar</button>&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          <a href="/listadoRecetas" class="btn btn-outline-danger rounded-pill m-2">Cancelar</a>
          </form>
      </div>

    </div>
</div>
<!-- Sales Chart End -->



<script type="text/javascript">
  $("#frm_nuevo_historial").validate({
    errorPlacement: function(error, element) {
      var errorContainerId = 'error-' + element.attr('name');
      error.appendTo('#' + errorContainerId);
    },
    rules:{
      "peso":{
        required:true
      },
      "altura":{
        required:true,
      },
      "id_cita":{
        required:true
      },
      "fechaCreacion":{
        required:true,
      }
    },
    messages:{
      "peso":{
        required:"Debe ingresar el peso"
      },
      "altura":{
        required:"Debe ingresar la altura",
      },
      "id_cita":{
        required:"Debe seleccionar la cita"
      },
      "fechaCreacion":{
        required:"Debe ingresar la fecha de la receta",
      }
    }
  });
</script>


{% endblock %}

Aplicaciones/Historiales/templates/listadoRecetas.html
{% extends './plantilla.html' %}
{% block contenido %}



<!-- Sales Chart Start -->
<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
      <div class="bg-light text-center rounded p-4">
          <div class="d-flex align-items-center justify-content-between mb-4">
              <h6 class="mb-0">Añadir Receta</h6>
          </div>
          <form class="" action="/guardarReceta/" enctype="multipart/form-data" method="post" id="frm_nuevo_historial">
            {% csrf_token %}
            <div class="form-floating mb-3">
              <input type="date" class="form-control" name="fechaCreacion" id="fechaCreacion"placeholder="name@example.com" required>
              <label for="fechaCreacion">Fecha de Creación</label>
              <div id="error-fechaCreacion" class="error-messages"></div>
            </div>
            <script>
              var fechaActual = new Date();
              var inputFecha = document.getElementById('fechaCreacion');

              inputFecha.onchange = function() {
                var fechaSeleccionada = new Date(this.value);
                if (fechaSeleccionada > fechaActual) {
                  inputFecha.value = fechaActual.toISOString().slice(0, 10);
                }
              };
            </script>


            <div class="form-floating mb-3">
              <input type="number" class="form-control" name="peso" id="peso"placeholder="name@example.com" required>
              <label for="peso">Peso del paciente (Klg)</label>
              <div id="error-peso" class="error-messages"></div>
            </div>

            <div class="form-floating mb-3">
              <input type="number" class="form-control" name="altura" id="altura"placeholder="name@example.com" required>
              <label for="altura">Altura del paciente (m)</label>
              <div id="error-altura" class="error-messages"></div>
            </div>

            <div class="form-floating mb-3">
              <select  name="id_cita"  id="id_cita" class="form-control" required>
                      <option value=""> Seleccionar la cita del paciente</option>
                      {% for cita in citas %}
                      <option value="{{cita.idCita}}">De {{cita.doctor.nombreDoctor}} el {{cita.fechaCreacion}}</option>
                      {% endfor %}
              </select>
              <label for="id_historial">Cita</label>
              <div id="error-id_cita" class="error-messages"></div>
            </div>

            <br>
            <button type="submit" name="button" class="btn btn-outline-info rounded-pill m-2">Guardar</button>&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          <button type="reset" name="button" class="btn btn-outline-danger rounded-pill m-2">Cancelar</button>
          </form>
      </div>

    </div>
</div>
<!-- Sales Chart End -->


<!-- Recent Sales Start -->
<div class="container-fluid pt-4 px-4">
    <div class="bg-light text-center rounded p-4">
        <div class="d-flex align-items-center justify-content-between mb-4">
            <h6 class="mb-0">Registro de Recetas</h6>
        </div>
        <div class="table-responsive">
            <table class="table text-start align-middle table-bordered table-hover mb-0" id="tbl_repr">
                <thead>
                    <tr class="text-dark">
                        <th scope="col">ID</th>
                        <th scope="col">FECHA DE CREACIÓN</th>
                        <th scope="col">PESO</th>
                        <th scope="col">ALTURA</th>
                        <th scope="col">RECETADO POR:</th>
                        <th scope="col">ACCIONES</th>
                    </tr>
                </thead>
                <tbody>
                  {% for receta in recetas %}
                  <tr>
                    <td>{{receta.idReceta}}</td>
                    <td>{{receta.fechaCreacion}}</td>
                    <td>{{receta.peso}}</td>
                    <td>{{receta.altura}}</td>
                    <td>{{receta.cita.doctor}}</td>
                    <td>
                      <a href="/editarReceta/{{ receta.idReceta }}" class="btn btn-outline-success rounded-pill"><i class="fas fa-edit"></i></a>
                      <a href="javascript:void(0)"onclick="eliminarReceta('/eliminarReceta/{{receta.idReceta}}');" class="btn btn-outline-danger rounded-pill"><i class="fa fa-trash"></i></a>
                    </td>
                  </tr>
          {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<script type="text/javascript">
        function eliminarReceta(url){
          iziToast.question({
              timeout: 15000,
              close: true,
              overlay: true,
              displayMode: 'once',
              id: 'question',
              zindex: 999,
              title: 'CONFIRMACIÓN',
              message: '¿Está seguro de eliminar la <b>receta </b> seleccionada?',
              position: 'center',
              buttons: [
                  ['<button><b>SI</b></button>', function (instance, toast) {
                      instance.hide({ transitionOut: 'fadeOut' }, toast, 'button');
                      window.location.href=url;
                  }, true],
                  ['<button>NO</button>', function (instance, toast) {

                      instance.hide({ transitionOut: 'fadeOut' }, toast, 'button');

                  }],
              ]
          });
        }


{% if messages %}
    {% for message in messages %}
        iziToast.success({
            title: 'Éxito',
            message: '{{ message }}',
            position: 'topRight',
        });
    {% endfor %}
{% endif %}
  </script>

  <script type="text/javascript">
    $("#frm_nuevo_historial").validate({
      errorPlacement: function(error, element) {
        var errorContainerId = 'error-' + element.attr('name');
        error.appendTo('#' + errorContainerId);
      },
      rules:{
        "peso":{
          required:true
        },
        "altura":{
          required:true,
        },
        "id_cita":{
          required:true
        },
        "fechaCreacion":{
          required:true,
        }
      },
      messages:{
        "peso":{
          required:"Debe ingresar el peso"
        },
        "altura":{
          required:"Debe ingresar la altura",
        },
        "id_cita":{
          required:"Debe seleccionar la cita"
        },
        "fechaCreacion":{
          required:"Debe ingresar la fecha de la receta",
        }
      }
    });
  </script>

  <script type="text/javascript">
          $(document).ready(function() {
              $('#tbl_repr').DataTable( {
                  dom: 'Bfrtip',
                  buttons: [
                      {
                          extend: 'pdfHtml5',
                          text: '<i class="fa-solid fa-file-pdf"></i> PDF',
                          className: 'btn btn-outline-primary',
                          messageTop: 'Doctores de MediKid ',
                          title:'INFORMACIÓN MEDIKID'
                      },
                      {
                          extend: 'print',
                          text: '<i class="fa-solid fa-print"></i> Imprimir',
                          className: 'btn btn-outline-primary',
                          messageTop: 'Doctores de MediKid ',
                          title:'INFORMACIÓN MEDIKID'
                      },
                      {
                          extend: 'csv',
                          text: '<i class="fa-solid fa-file-csv"></i> CSV',
                          className: 'btn btn-outline-primary',
                          messageTop: 'Doctores de MediKid ',
                          title:'INFORMACIÓN MEDIKID'
                      }
                  ],
                  language: {
                      url: "https://cdn.datatables.net/plug-ins/1.10.25/i18n/Spanish.json"
                  },
                  initComplete: function () {
                    $('.dataTables_filter input[type="search"]').addClass('form-control');
                  }
              } );
          } );
      </script>
{% endblock %}